package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", schema = "reportes", uniqueConstraints = @UniqueConstraint(columnNames = "strnit"))
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
	private String strnombre;
	private String strnit;
	private String strdireccion;
	private String strciudad;
	private String strcontacto;
	private String strtelefono;

	private Set<Registro> registros = new HashSet<Registro>(0);

	public Cliente() {
	}

	public Cliente(int intid) {
		this.intid = intid;
	}

	public Cliente(int intid, String strnombre, String strnit, String strdireccion, String strciudad, String strcontacto, String strtelefono,
			Set<Registro> registros) {
		super();
		this.intid = intid;
		this.strnombre = strnombre;
		this.strnit = strnit;
		this.strdireccion = strdireccion;
		this.strciudad = strciudad;
		this.strcontacto = strcontacto;
		this.strtelefono = strtelefono;
		this.registros = registros;
	}

	@Id
	@SequenceGenerator(name = "cliente_intid_seq", sequenceName = "reportes.cliente_intid_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cliente_intid_seq")
	@Column(name = "intid", unique = true, nullable = false)
	public int getIntid() {
		return this.intid;
	}

	public void setIntid(int intid) {
		this.intid = intid;
	}

	@Column(name = "strnombre", length = 100)
	public String getStrnombre() {
		return this.strnombre;
	}

	public void setStrnombre(String strnombre) {
		this.strnombre = strnombre;
	}

	@Column(name = "strnit", unique = true, length = 50)
	public String getStrnit() {
		return this.strnit;
	}

	public void setStrnit(String strnit) {
		this.strnit = strnit;
	}

	@Column(name = "strdireccion", length = 100)
	public String getStrdireccion() {
		return strdireccion;
	}

	public void setStrdireccion(String strdireccion) {
		this.strdireccion = strdireccion;
	}

	@Column(name = "strciudad", length = 100)
	public String getStrciudad() {
		return strciudad;
	}

	public void setStrciudad(String strciudad) {
		this.strciudad = strciudad;
	}

	@Column(name = "strcontacto", length = 100)
	public String getStrcontacto() {
		return strcontacto;
	}

	public void setStrcontacto(String strcontacto) {
		this.strcontacto = strcontacto;
	}

	@Column(name = "strtelefono", length = 100)
	public String getStrtelefono() {
		return strtelefono;
	}

	public void setStrtelefono(String strtelefono) {
		this.strtelefono = strtelefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Registro> getRegistros() {
		return this.registros;
	}

	public void setRegistros(Set<Registro> registros) {
		this.registros = registros;
	}

}
