package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Llanta generated by hbm2java
 */
/**
 * @author David Andres
 * 
 */
@Entity
@Table(name = "llanta", schema = "reportes", uniqueConstraints = @UniqueConstraint(columnNames = "strnombre"))
public class Llanta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
	private String strnombre;
	private Set<Registro> registros = new HashSet<Registro>(0);

	public Llanta() {
	}

	public Llanta(int intid) {
		this.intid = intid;
	}

	public Llanta(int intid, String strnombre, Set<Registro> registros) {
		this.intid = intid;
		this.strnombre = strnombre;
		this.registros = registros;
	}

	@Id
	@SequenceGenerator(name = "llanta_intid_seq", sequenceName = "reportes.llanta_intid_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "llanta_intid_seq")
	@Column(name = "intid", unique = true, nullable = false)
	public int getIntid() {
		return this.intid;
	}

	public void setIntid(int intid) {
		this.intid = intid;
	}

	@Column(name = "strnombre", unique = true, length = 50)
	public String getStrnombre() {
		return this.strnombre;
	}

	public void setStrnombre(String strnombre) {
		this.strnombre = strnombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "llanta")
	public Set<Registro> getRegistros() {
		return this.registros;
	}

	public void setRegistros(Set<Registro> registros) {
		this.registros = registros;
	}

	@Override
	public String toString() {
		return "Llanta [intid=" + intid + ", strnombre=" + strnombre + "]";
	}

}
