package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametrica generated by hbm2java
 */
@Entity
@Table(name = "parametrica", schema = "autenticacion")
public class Parametrica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
	private String strnombre;
	private String strvalor;
	private String strtitle;
	private String strdescripcion;

	public Parametrica() {
	}

	public Parametrica(int intid) {
		this.intid = intid;
	}

	public Parametrica(int intid, String strnombre, String strvalor, String strtitle, String strdescripcion) {
		this.intid = intid;
		this.strnombre = strnombre;
		this.strvalor = strvalor;
		this.strtitle = strtitle;
		this.strdescripcion = strdescripcion;
	}

	@Id
	@Column(name = "intid", unique = true, nullable = false)
	public int getIntid() {
		return this.intid;
	}

	public void setIntid(int intid) {
		this.intid = intid;
	}

	@Column(name = "strnombre")
	public String getStrnombre() {
		return this.strnombre;
	}

	public void setStrnombre(String strnombre) {
		this.strnombre = strnombre;
	}

	@Column(name = "strvalor")
	public String getStrvalor() {
		return this.strvalor;
	}

	public void setStrvalor(String strvalor) {
		this.strvalor = strvalor;
	}

	@Column(name = "strdescripcion")
	public String getStrdescripcion() {
		return this.strdescripcion;
	}

	public void setStrdescripcion(String strdescripcion) {
		this.strdescripcion = strdescripcion;
	}

	@Column(name = "strtitle")
	public String getStrtitle() {
		return strtitle;
	}

	public void setStrtitle(String strtitle) {
		this.strtitle = strtitle;
	}

}
