package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "registro", schema = "reportes")
public class Registro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
	private Llanta llanta;
	private Rin rin;
	private Cliente cliente;
	private Integer intcertificado;
	private BigDecimal numpeso;
	private Date datefecha;
	private Integer intunidades;
	
	public Registro() {
	}

	public Registro(int intid) {
		this.intid = intid;
	}

	public Registro(int intid, Llanta llanta, Rin rin, Cliente cliente, Integer intcertificado, BigDecimal numpeso, Date datefecha,
			Integer intunidades) {
		this.intid = intid;
		this.llanta = llanta;
		this.rin = rin;
		this.cliente = cliente;
		this.intcertificado = intcertificado;
		this.numpeso = numpeso;
		this.datefecha = datefecha;
		this.intunidades = intunidades;
	}

	@Id
	@SequenceGenerator(name="registro_intid_seq", sequenceName = "reportes.registro_intid_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="registro_intid_seq")
	@Column(name = "intid", unique = true, nullable = false)
	public int getIntid() {
		return this.intid;
	}

	public void setIntid(int intid) {
		this.intid = intid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intidllanta")
	public Llanta getLlanta() {
		return this.llanta;
	}

	public void setLlanta(Llanta llanta) {
		this.llanta = llanta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intidrin")
	public Rin getRin() {
		return this.rin;
	}

	public void setRin(Rin rin) {
		this.rin = rin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intidcliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "intcertificado")
	public Integer getIntcertificado() {
		return this.intcertificado;
	}

	public void setIntcertificado(Integer intcertificado) {
		this.intcertificado = intcertificado;
	}

	@Column(name = "numpeso", precision = 5)
	public BigDecimal getNumpeso() {
		return this.numpeso;
	}

	public void setNumpeso(BigDecimal numpeso) {
		this.numpeso = numpeso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datefecha", length = 13)
	public Date getDatefecha() {
		return this.datefecha;
	}

	public void setDatefecha(Date datefecha) {
		this.datefecha = datefecha;
	}

	@Column(name = "intunidades")
	public Integer getIntunidades() {
		return this.intunidades;
	}

	public void setIntunidades(Integer intunidades) {
		this.intunidades = intunidades;
	}

}
