package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tercero generated by hbm2java
 */
@Entity
@Table(name = "tercero", schema = "autenticacion")
public class Tercero implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
	private TipoTecero tipoTecero;
	private Boolean boolestado;
	private Date datefechanacimiento;
	private Date dateusuariocreacion;
	private String intidentificacion;
	private String strapellido1;
	private String strapellido2;
	private String stremail;
	private String strmovil;
	private String strmovil2;
	private String strnombre1;
	private String strnombre2;
	private Character chargenero;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Tercero() {
	}

	public Tercero(int intid, String intidentificacion) {
		this.intid = intid;
		this.intidentificacion = intidentificacion;
	}

	public Tercero(int intid, TipoTecero tipoTecero, Boolean boolestado, Date datefechanacimiento, Date dateusuariocreacion,
			String intidentificacion, String strapellido1, String strapellido2, String stremail, String strmovil, String strmovil2,
			String strnombre1, String strnombre2, Character chargenero, Set<Usuario> usuarios) {
		this.intid = intid;
		this.tipoTecero = tipoTecero;
		this.boolestado = boolestado;
		this.datefechanacimiento = datefechanacimiento;
		this.dateusuariocreacion = dateusuariocreacion;
		this.intidentificacion = intidentificacion;
		this.strapellido1 = strapellido1;
		this.strapellido2 = strapellido2;
		this.stremail = stremail;
		this.strmovil = strmovil;
		this.strmovil2 = strmovil2;
		this.strnombre1 = strnombre1;
		this.strnombre2 = strnombre2;
		this.chargenero = chargenero;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "intid", unique = true, nullable = false)
	public int getIntid() {
		return this.intid;
	}

	public void setIntid(int intid) {
		this.intid = intid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idtipotercero")
	public TipoTecero getTipoTecero() {
		return this.tipoTecero;
	}

	public void setTipoTecero(TipoTecero tipoTecero) {
		this.tipoTecero = tipoTecero;
	}

	@Column(name = "boolestado")
	public Boolean getBoolestado() {
		return this.boolestado;
	}

	public void setBoolestado(Boolean boolestado) {
		this.boolestado = boolestado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datefechanacimiento", length = 13)
	public Date getDatefechanacimiento() {
		return this.datefechanacimiento;
	}

	public void setDatefechanacimiento(Date datefechanacimiento) {
		this.datefechanacimiento = datefechanacimiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateusuariocreacion", length = 13)
	public Date getDateusuariocreacion() {
		return this.dateusuariocreacion;
	}

	public void setDateusuariocreacion(Date dateusuariocreacion) {
		this.dateusuariocreacion = dateusuariocreacion;
	}

	@Column(name = "intidentificacion", nullable = false, length = 20)
	public String getIntidentificacion() {
		return this.intidentificacion;
	}

	public void setIntidentificacion(String intidentificacion) {
		this.intidentificacion = intidentificacion;
	}

	@Column(name = "strapellido1", length = 50)
	public String getStrapellido1() {
		return this.strapellido1;
	}

	public void setStrapellido1(String strapellido1) {
		this.strapellido1 = strapellido1;
	}

	@Column(name = "strapellido2", length = 50)
	public String getStrapellido2() {
		return this.strapellido2;
	}

	public void setStrapellido2(String strapellido2) {
		this.strapellido2 = strapellido2;
	}

	@Column(name = "stremail", length = 50)
	public String getStremail() {
		return this.stremail;
	}

	public void setStremail(String stremail) {
		this.stremail = stremail;
	}

	@Column(name = "strmovil", length = 20)
	public String getStrmovil() {
		return this.strmovil;
	}

	public void setStrmovil(String strmovil) {
		this.strmovil = strmovil;
	}

	@Column(name = "strmovil2", length = 20)
	public String getStrmovil2() {
		return this.strmovil2;
	}

	public void setStrmovil2(String strmovil2) {
		this.strmovil2 = strmovil2;
	}

	@Column(name = "strnombre1", length = 50)
	public String getStrnombre1() {
		return this.strnombre1;
	}

	public void setStrnombre1(String strnombre1) {
		this.strnombre1 = strnombre1;
	}

	@Column(name = "strnombre2", length = 50)
	public String getStrnombre2() {
		return this.strnombre2;
	}

	public void setStrnombre2(String strnombre2) {
		this.strnombre2 = strnombre2;
	}

	@Column(name = "chargenero", length = 1)
	public Character getChargenero() {
		return this.chargenero;
	}

	public void setChargenero(Character chargenero) {
		this.chargenero = chargenero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
