package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTecero generated by hbm2java
 */
@Entity
@Table(name = "tipo_tecero", schema = "autenticacion")
public class TipoTecero implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
	private String strnombre;
	private Set<Tercero> terceros = new HashSet<Tercero>(0);

	public TipoTecero() {
	}

	public TipoTecero(int intid) {
		this.intid = intid;
	}

	public TipoTecero(int intid, String strnombre, Set<Tercero> terceros) {
		this.intid = intid;
		this.strnombre = strnombre;
		this.terceros = terceros;
	}

	@Id
	@Column(name = "intid", unique = true, nullable = false)
	public int getIntid() {
		return this.intid;
	}

	public void setIntid(int intid) {
		this.intid = intid;
	}

	@Column(name = "strnombre", length = 50)
	public String getStrnombre() {
		return this.strnombre;
	}

	public void setStrnombre(String strnombre) {
		this.strnombre = strnombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTecero")
	public Set<Tercero> getTerceros() {
		return this.terceros;
	}

	public void setTerceros(Set<Tercero> terceros) {
		this.terceros = terceros;
	}

}
