package com.ecowheel.system.model;

// Generated 25/12/2016 01:08:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "autenticacion")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idusuario;
	private Tercero tercero;
	private Boolean boolestado;
	private Date datefchaCrcion;
	private Date datefchaVncmnto;
	private String strlogin;
	private String strpassword;

	public Usuario() {
	}

	public Usuario(int idusuario, String strlogin, String strpassword) {
		this.idusuario = idusuario;
		this.strlogin = strlogin;
		this.strpassword = strpassword;
	}

	public Usuario(int idusuario, Tercero tercero, Boolean boolestado, Date datefchaCrcion, Date datefchaVncmnto, String strlogin, String strpassword) {
		this.idusuario = idusuario;
		this.tercero = tercero;
		this.boolestado = boolestado;
		this.datefchaCrcion = datefchaCrcion;
		this.datefchaVncmnto = datefchaVncmnto;
		this.strlogin = strlogin;
		this.strpassword = strpassword;
	}

	@Id
	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtercero")
	public Tercero getTercero() {
		return this.tercero;
	}

	public void setTercero(Tercero tercero) {
		this.tercero = tercero;
	}

	@Column(name = "boolestado")
	public Boolean getBoolestado() {
		return this.boolestado;
	}

	public void setBoolestado(Boolean boolestado) {
		this.boolestado = boolestado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datefcha_crcion", length = 13)
	public Date getDatefchaCrcion() {
		return this.datefchaCrcion;
	}

	public void setDatefchaCrcion(Date datefchaCrcion) {
		this.datefchaCrcion = datefchaCrcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datefcha_vncmnto", length = 13)
	public Date getDatefchaVncmnto() {
		return this.datefchaVncmnto;
	}

	public void setDatefchaVncmnto(Date datefchaVncmnto) {
		this.datefchaVncmnto = datefchaVncmnto;
	}

	@Column(name = "strlogin", nullable = false, length = 600)
	public String getStrlogin() {
		return this.strlogin;
	}

	public void setStrlogin(String strlogin) {
		this.strlogin = strlogin;
	}

	@Column(name = "strpassword", nullable = false, length = 600)
	public String getStrpassword() {
		return this.strpassword;
	}

	public void setStrpassword(String strpassword) {
		this.strpassword = strpassword;
	}

}
